import { createElement } from 'lwc';
import LWC_07_CustomLinksModalConfirmation from 'c/lWC_07_CustomLinksModalConfirmation';

describe('c-l-w-c-07-custom-links-modal-confirmation', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-l-w-c-07-custom-links-modal-confirmation', {
            is: LWC_07_CustomLinksModalConfirmation
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});